spring: #配置eureka的名字
  application:
    name: eruka-server
eureka:
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false
    #读取对等节点服务器复制的超时的时间，单位为毫秒，默认为200
    peer-node-read-timeout-ms: 10000
  client:
    #register-with-eureka: false #是否要将自身的实例信息注册到Eureka服务端
    #fetch-registry: false #是否从Eureka服务端获取注册信息
    service-url: # 配置其他Eureka服务的地址，而不是自己，比如8762
      defaultZone: http://127.0.0.1:8763/eureka/  
  instance:
    lease-renewal-interval-in-seconds: 1 #Eureka客户端向服务端发送心跳的时间间隔，单位为秒
    lease-expiration-duration-in-seconds: 2 #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒。超过该时间之后服务端会将该服务实例从服务清单中剔除，从而禁止服务调用请求被发送到该实例上